### ISSUE TITLE
Can't scroll right to see more devices

### ISSUE THREAD

**Issue by RoyMudie** [sicsix/BYOJoystick#15] opened 2024-09-03 10:43 UTC
I've got... a couple... of devices attached, and as such I can't scroll to the right to see all of them.

![image](https://github.com/user-attachments/assets/45694d64-5cb2-43d7-ab5a-c8619588f348)

**Comment by sicsix** [comment] 2024-09-08 10:35
Duplicate of #16

**Closed by sicsix** 2024-09-08 10:35 UTC

**Comment by RoyMudie** [comment] 2025-02-28 15:00
Hey @sicsix I'm just away to recommend this mod [here](https://www.reddit.com/r/hoggit/comments/1izzyeo/how_many_of_you_would_consider_playing_vtol_vr_if/) and noticed this ticket is closed.

This is not a duplicate of #16 as when I solved the issue of screen resolution, I still can't scroll right to see all my devices, as shown here:

![Image](https://github.com/user-attachments/assets/51eeea77-1143-4f74-8449-d49d5dab202f)

For the siming community, that have ALL the gear, it's so close to working - but I can't bind my throttle without having to go behind my desk to unplug half my devices...
