### ISSUE TITLE
No device names at the top of the columns

### ISSUE THREAD

**Issue by RoyMudie** [sicsix/BYOJoystick#14] opened 2024-09-03 10:43 UTC
Not sure if this is because I'm on an ultrawide, but there's no device names at the top of the column making it hard to know what device I'm selecting:

![image](https://github.com/user-attachments/assets/555cbe30-bf0a-41d3-ba2d-ed580889b70c)

**Comment by sicsix** [comment] 2024-09-08 10:35
Duplicate of #16

**Closed by sicsix** 2024-09-08 10:35 UTC
